import { describe, expect, it } from 'vitest';
import {
  addTailwindVite,
  createNextProviders,
  wireNextLayout,
  wrapEntryWithProvider,
  stripNextFont,
  stripNextFontCss,
  setNextTitle,
} from './entry-patch';

// Literal output of `npm create vite@latest -- --template react-ts`.
const VITE_MAIN = `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`;

const VITE_CONFIG = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
})
`;

// Literal output of `create-next-app --ts --tailwind --app`.
const NEXT_LAYOUT = `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={\`\${geistSans.variable} \${geistMono.variable} antialiased\`}
      >
        {children}
      </body>
    </html>
  );
}
`;

describe('wrapEntryWithProvider (Vite main.tsx)', () => {
  it('imports ThemeProvider and wraps <App />, preserving indentation', () => {
    const { content, changed } = wrapEntryWithProvider(VITE_MAIN);
    expect(changed).toBe(true);
    expect(content).toContain("import { ThemeProvider } from '@offthegully/veneerui'");
    expect(content).toContain('    <ThemeProvider>\n      <App />\n    </ThemeProvider>');
    // import goes after the existing imports, before the render call
    expect(content.indexOf('ThemeProvider')).toBeLessThan(content.indexOf('createRoot(document'));
  });

  it('is idempotent — a second run is a no-op', () => {
    const once = wrapEntryWithProvider(VITE_MAIN).content;
    expect(wrapEntryWithProvider(once).changed).toBe(false);
  });

  it('bails on an unfamiliar entry (no <App />)', () => {
    const r = wrapEntryWithProvider("createRoot(el).render(<Main />)\n");
    expect(r.changed).toBe(false);
    expect(r.reason).toMatch(/App/);
  });
});

describe('addTailwindVite (vite.config.ts)', () => {
  it('adds the @tailwindcss/vite plugin', () => {
    const { content, changed } = addTailwindVite(VITE_CONFIG);
    expect(changed).toBe(true);
    expect(content).toContain("import tailwindcss from '@tailwindcss/vite'");
    expect(content).toMatch(/plugins:\s*\[tailwindcss\(\), react\(\)\]/);
  });

  it('is idempotent', () => {
    const once = addTailwindVite(VITE_CONFIG).content;
    expect(addTailwindVite(once).changed).toBe(false);
  });

  it('bails when there is no plugins array', () => {
    const r = addTailwindVite("export default defineConfig({})\n");
    expect(r.changed).toBe(false);
    expect(r.reason).toMatch(/plugins/);
  });

  it('composes with addViteAntiFlash to a working plugins array', async () => {
    const { addViteAntiFlash } = await import('./patch');
    const withTw = addTailwindVite(VITE_CONFIG).content;
    const withBoth = addViteAntiFlash(withTw).content;
    expect(withBoth).toContain("import tailwindcss from '@tailwindcss/vite'");
    expect(withBoth).toContain("import { veneer } from '@offthegully/veneerui/vite'");
    expect(withBoth).toMatch(/plugins:\s*\[veneer\(\), tailwindcss\(\), react\(\)\]/);
  });
});

describe('createNextProviders', () => {
  it('is a client component exporting a ThemeProvider wrapper', () => {
    const out = createNextProviders();
    expect(out.startsWith("'use client'")).toBe(true);
    expect(out).toContain("import { ThemeProvider } from '@offthegully/veneerui'");
    expect(out).toContain('export function Providers(');
    expect(out).toContain('<ThemeProvider>{children}</ThemeProvider>');
  });
});

describe('wireNextLayout (app/layout.tsx)', () => {
  const result = wireNextLayout(NEXT_LAYOUT);

  it('imports Providers and the anti-flash script', () => {
    expect(result.changed).toBe(true);
    expect(result.content).toContain("import { Providers } from './providers'");
    expect(result.content).toContain("import { AntiFlashScript } from '@offthegully/veneerui/next'");
  });

  it('adds suppressHydrationWarning to <html> (the required SSR interlock)', () => {
    expect(result.content).toContain('<html lang="en" suppressHydrationWarning>');
  });

  it('renders <AntiFlashScript /> inside a <head>', () => {
    expect(result.content).toMatch(/<head>\s*<AntiFlashScript \/>\s*<\/head>/);
  });

  it('wraps the body {children} in <Providers> — and not the destructured prop', () => {
    expect(result.content).toContain('<Providers>{children}</Providers>');
    // the function parameter `{\n  children,\n}` must remain untouched
    expect(result.content).toContain('RootLayout({\n  children,\n}');
    // exactly one Providers wrap
    expect(result.content.match(/<Providers>/g)).toHaveLength(1);
  });

  it('is idempotent — a second run is a no-op', () => {
    expect(wireNextLayout(result.content).changed).toBe(false);
  });

  it('bails on an unfamiliar layout (no <html>)', () => {
    const r = wireNextLayout('export default function L({children}){ return children }');
    expect(r.changed).toBe(false);
    expect(r.reason).toMatch(/html/);
  });
});

// Literal output of `create-next-app --ts --tailwind --app`.
const NEXT_GLOBALS = `@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --font-sans: var(--font-geist-sans);
  --font-mono: var(--font-geist-mono);
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: Arial, Helvetica, sans-serif;
}
`;

describe('stripNextFont (app/layout.tsx)', () => {
  it('removes the next/font import, the Font({…}) consts, and the ${x.variable} classes', () => {
    const out = stripNextFont(NEXT_LAYOUT);
    expect(out.changed).toBe(true);
    expect(out.content).not.toMatch(/next\/font/);
    expect(out.content).not.toMatch(/geist/i);
    expect(out.content).not.toMatch(/\.variable/);
    // the rest of the className survives
    expect(out.content).toMatch(/className=\{`\s*antialiased`\}/);
  });

  it('is idempotent and a no-op when there is no next/font', () => {
    const once = stripNextFont(NEXT_LAYOUT).content;
    expect(stripNextFont(once).changed).toBe(false);
    expect(stripNextFont('export default function L(){ return null }').changed).toBe(false);
  });
});

describe('stripNextFontCss (app/globals.css)', () => {
  it('removes the geist font remap and the hard body font-family', () => {
    const out = stripNextFontCss(NEXT_GLOBALS);
    expect(out.changed).toBe(true);
    expect(out.content).not.toMatch(/--font-sans:\s*var\(--font-geist/);
    expect(out.content).not.toMatch(/--font-mono:\s*var\(--font-geist/);
    expect(out.content).not.toMatch(/font-family:\s*Arial/);
    // unrelated rules survive
    expect(out.content).toMatch(/--color-background: var\(--background\)/);
    expect(stripNextFontCss(out.content).changed).toBe(false); // idempotent
  });
});

describe('setNextTitle (app/layout.tsx)', () => {
  it('replaces the default title and preserves a custom one', () => {
    const out = setNextTitle(NEXT_LAYOUT, 'My App');
    expect(out.changed).toBe(true);
    expect(out.content).toMatch(/title:\s*"My App"/);
    expect(setNextTitle(out.content, 'My App').changed).toBe(false); // custom title untouched
  });
});
